Repository ES2-UFPI/WarTank, pull requests merged in 2022-09, with the labels that each got.

#48 Add setup to automated tests #40
  Assets/AudioClips/ExplosionSoundEffect2.wav.meta
  Assets/Tests.meta
  Assets/Tests/EditorMode.meta
  Assets/Tests/EditorMode/BasicTests.cs
  Assets/Tests/EditorMode/BasicTests.cs.meta
  Assets/Tests/EditorMode/EditorMode.asmdef
  Assets/Tests/EditorMode/EditorMode.asmdef.meta
  Assets/Tests/PlayMode.meta
  Assets/Tests/PlayMode/BasicPlayModeTests.cs
  Assets/Tests/PlayMode/BasicPlayModeTests.cs.meta
  Assets/Tests/PlayMode/Tests.asmdef
  Assets/Tests/PlayMode/Tests.asmdef.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
Labels: tests

#52 Paulo andre#11
  Assets/AudioClips/simian-segue-restored.mp3
  Assets/AudioClips/simian-segue-restored.mp3.meta
  Assets/AudioClips/station-menu-music.mp3
  Assets/AudioClips/station-menu-music.mp3.meta
  Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion
  Assets/Prefab/Player/Player.prefab
  Assets/Scenes/Flow.unity
  Assets/Scenes/Menu.unity
  Assets/Scripts/FireSystem/TankCannon.cs
  Assets/Scripts/Managers/SoundManager.cs
  Assets/Scripts/Managers/SoundManager.cs.meta
  Assets/Scripts/Player/PlayerMoviment.cs
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#59 Fix project to start with new arena #55
  Assets/Materials/Map materials/Central box 1.mat
  Assets/Materials/Map materials/Leaf.mat
  Assets/Materials/Map materials/Tree.mat
  Assets/Scenes/Flow.unity
  Assets/Scripts/Managers/PlayerSpawner.cs
  UserSettings/Layouts/default-2021.dwlt
Labels: bug

#63 Added: Camera follow behaviour #58
  Assets/Scenes/Flow.unity
  Assets/Scripts/Managers/PlayerSpawner.cs
  Assets/Scripts/Miscs/CameraFollow.cs
  Assets/Scripts/Miscs/CameraFollow.cs.meta
  Assets/Scripts/Player/PlayerBehavirour.cs
Labels: enhancement
